# Generated by Django 3.1.4 on 2021-03-24 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockType', models.CharField(choices=[('A', 'StockA'), ('B', 'StockB'), ('C', 'StockC'), ('D', 'StockD'), ('E', 'StockE'), ('F', 'StockF'), ('G', 'StockG')], max_length=1)),
                ('stockNumber', models.IntegerField(default=10000, verbose_name='stockNumber')),
            ],
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockType', models.CharField(choices=[('A', 'StockA'), ('B', 'StockB'), ('C', 'StockC'), ('D', 'StockD'), ('E', 'StockE'), ('F', 'StockF'), ('G', 'StockG')], max_length=1)),
                ('stockNumber', models.IntegerField(default=10000, verbose_name='stockNumber')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StocksRecipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockType', models.CharField(choices=[('A', 'StockA'), ('B', 'StockB'), ('C', 'StockC'), ('D', 'StockD'), ('E', 'StockE'), ('F', 'StockF'), ('G', 'StockG')], max_length=1)),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('soldAt', models.DateTimeField(default=django.utils.timezone.now, help_text='Format : YYYY-MM-DDThh:mm', verbose_name='dateTime')),
                ('tag', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_userstock', to='homeapp.userstocks')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_userstock', to='homeapp.userstocks')),
            ],
        ),
    ]
