# Generated by Django 3.1.7 on 2021-03-25 05:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('updatedAt', models.TimeField(default=datetime.datetime(2021, 3, 25, 5, 41, 8, 436599, tzinfo=utc), verbose_name='updatedAt')),
            ],
        ),
        migrations.CreateModel(
            name='Stocktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockId', models.CharField(max_length=20, unique=True, verbose_name='stockId')),
                ('stockName', models.CharField(max_length=256, verbose_name='stockName')),
            ],
        ),
        migrations.RemoveField(
            model_name='userstocks',
            name='username',
        ),
        migrations.RemoveField(
            model_name='orgstocks',
            name='stockNumber',
        ),
        migrations.AddField(
            model_name='orgstocks',
            name='stockAmount',
            field=models.IntegerField(default=0, verbose_name='stockAmount'),
        ),
        migrations.DeleteModel(
            name='StocksRecipts',
        ),
        migrations.DeleteModel(
            name='UserStocks',
        ),
        migrations.AddField(
            model_name='pricechange',
            name='is_linked',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.stocktype'),
        ),
        migrations.AlterField(
            model_name='orgstocks',
            name='stockType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeapp.stocktype'),
        ),
    ]
