# Generated by Django 3.1.7 on 2021-03-25 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20210325_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechange',
            name='updatedAt',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='updatedAt'),
        ),
    ]
