# Generated by Django 3.1.4 on 2021-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10)),
                ('additional_mobile_number', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField()),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
    ]
